version: "3.9"
services:
  backend:
    build: .
    image: voiceguard-backend:dev
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      ALLOWED_ORIGINS: "http://localhost:3000"
      WS_ALLOWED_ORIGINS: "http://localhost:3000"
      API_TOKEN: "devtoken"
      # Uncomment to enable ASR in container (ensure GPU or CPU ok)
      # LOAD_ASR_AT_START: "false"
      # ASR_MODEL_SIZE: "small"
      # ASR_COMPUTE_TYPE: "int8"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: ["gpu"]
